In [1]:
import numpy as np

In [2]:
def parse_input(file_name: str = 'example1.input.txt') -> str:
    grid = []
    with open(file_name, 'r', encoding='utf-8') as fin:
        for line in [line.strip() for line in fin if len(line.strip()) > 0]:
            grid.append([int(n) for n in line.strip()])
    return np.array(grid, dtype=int)

In [3]:
grid = parse_input()

print(grid)

[[0 1 2 3]
 [1 2 3 4]
 [8 7 6 5]
 [9 8 7 6]]


In [10]:
grid = parse_input('example2.input.txt')
print(grid)
xs, ys = np.where(grid == 0)
for x, y in zip(xs, ys):
    print(x, y)

[[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]]
0 2
0 4
2 4
4 6
5 2
5 5
6 0
6 6
7 1
