In [5]:
import numpy as np

In [6]:
def parse_input(file_name: str = 'example1.input.txt') -> str:
    grid = []
    with open(file_name, 'r', encoding='utf-8') as fin:
        for line in [line.strip() for line in fin if len(line.strip()) > 0]:
            grid.append([int(n) for n in line.strip()])
    return np.array(grid, dtype=int)

In [ ]:
class Node:
    def __init__(self, x, y, value) -> None:
        self.coordinates = tuple((x, y))
        self.x = x
        self.y = y
        self.value = value
        self.neighbors = []

    def __repr__(self):
        return "Node()"

    def __str__(self):
        return f"{self.value}: {self.coordinates}"

    def add_neighbor(self, x, y, value) -> None:
        neighbor = Node(x, y, value)
        self.neighbors.append(neighbor)

    def get_x(self) -> int:
        return self.x

    def get_y(self) -> int:
        return self.y

    def get_coordinates(self) -> tuple:
        return self.coordinates

In [8]:
grid = parse_input()

print(grid)

[[0 1 2 3]
 [1 2 3 4]
 [8 7 6 5]
 [9 8 7 6]]


In [16]:
nodes = []

for iy, ix in np.ndindex(grid.shape):
    nodes.append(Node(ix, iy, grid[iy, ix]))

for n in nodes: print(n)

0: (0, 0)
1: (1, 0)
2: (2, 0)
3: (3, 0)
1: (0, 1)
2: (1, 1)
3: (2, 1)
4: (3, 1)
8: (0, 2)
7: (1, 2)
6: (2, 2)
5: (3, 2)
9: (0, 3)
8: (1, 3)
7: (2, 3)
6: (3, 3)


In [10]:
grid = parse_input('example2.input.txt')
print(grid)
xs, ys = np.where(grid == 0)
for x, y in zip(xs, ys):
    print(x, y)

[[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]]
0 2
0 4
2 4
4 6
5 2
5 5
6 0
6 6
7 1
